### ISSUE TITLE
GLI Autocompletes partial commands

### ISSUE THREAD

**Issue by NickLaMuro** [sportngin/octopolo#34]
GLI has a feature to autocomplete a command it it doesn't find an exact match:

https://github.com/davetron5000/gli/blob/gli-2/lib/gli/command_finder.rb

This is a problem when running something like `op deploy` and thinking that it will do what you want.

There is no way to toggle this as of right now because it is a baked in feature of GLI.  We could possibly add a `op deploy` stub command that just barks at the user for trying a silly thing, but beyond that, we would have to fork GLI and make a pull-request to fix the issue.

**Comment by ChrisArcand** [comment]
Orly. I always thought that was just some bad regex on somebody's part. :+1: Contributing back to GLI.
