### ISSUE TITLE
Putting in an invalid jira ticket ID makes pull-request bomb hard

### ISSUE THREAD

**Issue by anfleene** [sportngin/octopolo#36]
So basically adding an invalid jira id throws up but still creates a Pull Request. It should probably not do that. It shouldn't fail so hard, and it shouldn't make a PR in a failure situation.

**Comment by ChrisArcand** [comment]
You mean '_shouldn't_ make a PR in a failure situation', right?

**Comment by anfleene** [comment]
![yes](https://p.gr-assets.com/540x540/fit/hostedimages/1398293722/9396284.gif)

**Comment by ChrisArcand** [comment]
This is somewhat related to https://github.com/sportngin/octopolo/issues/26 as well. Basically we need to make PR's not trainwreck every time something in that block breaks. Might peek at this next week for fun.

**Comment by anfleene** [comment]
agreed It leaves you a bit of a mess when things don't go as planned. accept-pull isn't much better

**Comment by astuyve** [comment]
Closing issue as fixed.

**Comment by chrisarcand** [comment]
Where's the commit that fixed this?

**Comment by astuyve** [comment]
referenced here: https://github.com/sportngin/octopolo/pull/84

**Comment by chrisarcand** [comment]
❤️
