### ISSUE TITLE
Upgrade Octokit

### ISSUE THREAD

**Issue by bbergstrom** [sportngin/octopolo#60]
octopolo is a major version behind on the critical octokit dependency.  We should upgrade it at some point before a deprecation becomes a problem.

https://github.com/octokit/octokit.rb/releases

Also, some bugs like https://github.com/octokit/octokit.rb/pull/538 are fixed in new releases which we have to implement work arounds for.

**Comment by astuyve** [comment]
Fixed here: https://github.com/sportngin/octopolo/pull/54/commits/749e6016febaddd8f3fed3c80f84abba26a40e76
closing issue.
