### ISSUE TITLE
Clone OpsWorks instances with octopolo

### ISSUE THREAD

**Issue by mykola42** [sportngin/octopolo#74]
New `clone-instance` command should:

- Ask which particular instance to clone
- Ask for a name for the new instance
- Ask if it should start the new instance
- Create a new instance with all the same settings as the existing one has (OpsWorks Layer, Instance type, Subnet, AMI, etc.)
- Start the new instance if it's been told to do so

**Comment by anfleene** [comment]
This is an opsicle thing not octopolo.
