### ISSUE TITLE
Octopolo should create the .octopolo.yml file if it doesn't exist

### ISSUE THREAD

**Issue by astuyve** [sportngin/octopolo#85]
Basically `new-branch` will die if `.octopolo.yml` or `.automation.yml` doesn't exist.
It works fine if the file is empty, so let's create a new one.

Potentially add it to .gitignore?

**Comment by chrisarcand** [comment]
Currently just outputs `*** WARNING: Could not find .octopolo.yml or .automation.yml ***`

I suggest adding a script to generate one, as you need basic info like the github org/repo. (`configure` or whatever)

Then add a prompt after the warning above to generate a new one _at the Git project root_:

`Would you like to generate one? [y/n]`

Would not automatically add to .gitignore (this is a project file, other people use it). You guys don't add it to gitignore in any of your projects ;)

**Comment by astuyve** [comment]
just gonna slide in here and close this

**Comment by chrisarcand** [comment]
![](http://gifs.chrisarcand.com/cry-clap-wwe.gif)

**Comment by astuyve** [comment]
![](https://i.redd.it/b8lbkixr4jg71.gif)

**Comment by NickLaMuro** [comment]
![image](https://user-images.githubusercontent.com/314014/129064547-37d3b9a5-90a2-4282-b8b0-f5874cac637c.png)
